/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface CreateUserDto {
    firebaseUid: string;
    name: string;
    email: string;
    photoUrl: string;
    isActive: boolean;
}

export interface UpdateUserDto {
}

export interface CreateTenantDto {
    name: string;
    slug: string;
    document: string;
    phone: string;
    email: string;
    logoUrl: string;
    isActive: boolean;
}

export interface UpdateTenantDto {
    name?: string;
    slug?: string;
    document?: string;
    phone?: string;
    email?: string;
    logoUrl?: string;
    isActive?: boolean;
}

export interface CreateTenantUserDto {
    tenantId: number;
    userId: number;
    role: string;
    isActive: boolean;
}

export interface UpdateTenantUserDto {
    tenantId?: number;
    userId?: number;
    role?: string;
    isActive?: boolean;
}

export interface CreateTenantSettingDto {
    tenantId: number;
    openingTime: string;
    closingTime: string;
    allowDelivery: boolean;
    allowPickup: boolean;
    allowDineIn: boolean;
}

export interface UpdateTenantSettingDto {
    tenantId?: number;
    openingTime?: string;
    closingTime?: string;
    allowDelivery?: boolean;
    allowPickup?: boolean;
    allowDineIn?: boolean;
}

export interface CreatePaymentMethodDto {
    tenantId: number;
    name: string;
    type: 'CREDIT_CARD' | 'DEBIT_CARD' | 'PIX' | 'CASH';
    isActive: boolean;
}

export interface UpdatePaymentMethodDto {
    tenantId?: number;
    name?: string;
    type?: 'CREDIT_CARD' | 'DEBIT_CARD' | 'PIX' | 'CASH';
    isActive?: boolean;
}

export interface CreateNeighborhoodDto {
    tenantId: number;
    name: string;
    deliveryFee: number;
    estimatedDeliveryTime: number;
    isActive: boolean;
}

export interface UpdateNeighborhoodDto {
    tenantId?: number;
    name?: string;
    deliveryFee?: number;
    estimatedDeliveryTime?: number;
    isActive?: boolean;
}

export interface CreateCategoryDto {
    tenantId: number;
    name: string;
    description: string;
    order: number;
    isActive: boolean;
}

export interface UpdateCategoryDto {
    tenantId?: number;
    name?: string;
    description?: string;
    order?: number;
    isActive?: boolean;
}

export interface CreateProductDto {
    tenantId: number;
    categoryId: number;
    name: string;
    description: string;
    price: number;
    imageUrl: string;
    isAvailable: boolean;
}

export interface UpdateProductDto {
    tenantId?: number;
    categoryId?: number;
    name?: string;
    description?: string;
    price?: number;
    imageUrl?: string;
    isAvailable?: boolean;
}

export interface CreateProductsOptionDto {
    tenantId: number;
    productId: number;
    name: string;
    price: number;
    isAvailable: boolean;
}

export interface UpdateProductsOptionDto {
    tenantId?: number;
    productId?: number;
    name?: string;
    price?: number;
    isAvailable?: boolean;
}

export interface CreateCustomerDto {
    tenantId: number;
    firstName: string;
    lastName: string;
    phone: string;
    email: string;
    document: string;
    neighborhoodId: number;
    address: string;
    number: string;
    complement: string;
    reference: string;
    isActive: boolean;
}

export interface UpdateCustomerDto {
    tenantId?: number;
    firstName?: string;
    lastName?: string;
    phone?: string;
    email?: string;
    document?: string;
    neighborhoodId?: number;
    address?: string;
    number?: string;
    complement?: string;
    reference?: string;
    isActive?: boolean;
}

export interface CreateOrderDto {
    tenantId: number;
    customerId: number;
    orderNumber: number;
    type: string;
    status: string;
    paymentMethodId: number;
    subtotal: number;
    discount: number;
    total: number;
    deliveryFee: number;
    notes: string;
    createdByUserId: number;
}

export interface UpdateOrderDto {
    tenantId?: number;
    customerId?: number;
    orderNumber?: number;
    type?: string;
    status?: string;
    paymentMethodId?: number;
    subtotal?: number;
    discount?: number;
    total?: number;
    deliveryFee?: number;
    notes?: string;
    createdByUserId?: number;
}

export interface CreateOrderItemDto {
    tenantId: number;
    orderId: number;
    productId: number;
    productName: string;
    quantity: number;
    unitPrice: number;
    total: number;
    notes: string;
}

export interface UpdateOrderItemDto {
    tenantId?: number;
    orderId?: number;
    productId?: number;
    productName?: string;
    quantity?: number;
    unitPrice?: number;
    total?: number;
    notes?: string;
}

export interface CreateOrderItemOptionDto {
    tenantId: number;
    orderItemId: number;
    productOptionId: number;
    productOptionName: string;
    unitPrice: number;
    quantity: number;
    total: number;
}

export interface UpdateOrderItemOptionDto {
    tenantId?: number;
    orderItemId?: number;
    productOptionId?: number;
    productOptionName?: string;
    unitPrice?: number;
    quantity?: number;
    total?: number;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
